include("/opt/homebrew/share/cmake/Modules/GoogleTestAddTests.cmake")
gtest_discover_tests_impl(
  TEST_TARGET [==[titancore_tests]==]
  TEST_EXECUTABLE [==[/Users/ps/Desktop/Projects/TitanCore/tests/titancore_tests]==]
  TEST_EXECUTOR [==[]==]
  TEST_WORKING_DIR [==[/Users/ps/Desktop/Projects/TitanCore/tests]==]
  TEST_EXTRA_ARGS [==[]==]
  TEST_PROPERTIES [==[]==]
  TEST_PREFIX [==[]==]
  TEST_SUFFIX [==[]==]
  TEST_FILTER [==[]==]
  NO_PRETTY_TYPES [==[FALSE]==]
  NO_PRETTY_VALUES [==[FALSE]==]
  TEST_LIST [==[titancore_tests_TESTS]==]
  CTEST_FILE [==[/Users/ps/Desktop/Projects/TitanCore/tests/titancore_tests_e3b0c442_tests.cmake]==]
  TEST_DISCOVERY_TIMEOUT [==[5]==]
  TEST_DISCOVERY_EXTRA_ARGS [==[]==]
  TEST_XML_OUTPUT_DIR [==[]==]
  TEST_JSON_OUTPUT_DIR [==[/Users/ps/Desktop/Projects/TitanCore/tests]==]
)
